In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
cd "/content/drive/MyDrive"

/content/drive/MyDrive

In [3]:
mkdir FakeNews

In [3]:
cd "/content/drive/MyDrive/FakeNews"

/content/drive/MyDrive/FakeNews

In [4]:
ls

Fake.csv  True.csv

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import nltk
import re
import string

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

from tensorflow import keras
from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense,Embedding,LSTM,Dropout

import warnings
warnings.filterwarnings('ignore')

In [6]:
real_data = pd.read_csv('True.csv')
fake_data = pd.read_csv('Fake.csv')

In [7]:
real_data.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [8]:
fake_data.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [9]:
real_data['target'] = 1
fake_data['target'] = 0

In [10]:
real_data.tail()

,title,text,subject,date,target
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

In [11]:
fake_data.tail()

,title,text,subject,date,target
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",0
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",0
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",0
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",0
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",0

In [12]:
#Merging the 2 datasets
data = pd.concat([real_data, fake_data], ignore_index=True, sort=False)
data.head()

,title,text,subject,date,target
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1

In [13]:
data.isnull().sum()

title      0
text       0
subject    0
date       0
target     0
dtype: int64

In [14]:
data['text']= data['subject'] + " " + data['title'] + " " + data['text']
del data['title']
del data['subject']
del data['date']
data.head()

                                                text  target
0  politicsNews As U.S. budget fight looms, Repub...       1
1  politicsNews U.S. military to accept transgend...       1
2  politicsNews Senior U.S. Republican senator: '...       1
3  politicsNews FBI Russia probe helped by Austra...       1
4  politicsNews Trump wants Postal Service to cha...       1

In [15]:
pip install bs4

Collecting bs4
  Downloading bs4-0.0.2-py2.py3-none-any.whl.metadata (411 bytes)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from bs4) (4.13.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->bs4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->bs4) (4.15.0)
Downloading bs4-0.0.2-py2.py3-none-any.whl (1.2 kB)
Installing collected packages: bs4
Successfully installed bs4-0.0.2

In [16]:
from bs4 import BeautifulSoup

In [17]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [18]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [19]:
nltk.download("stopwords")
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [20]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [21]:
#Removal of HTML Contents
def remove_html(text):
    soup = BeautifulSoup(text, "html.parser")
    return soup.get_text()

#Removal of Punctuation Marks
def remove_punctuations(text):
    return re.sub('\[[^]]*\]', '', text)

# Removal of Special Characters
def remove_characters(text):
    return re.sub("[^a-zA-Z]"," ",text)

#Removal of stopwords
def remove_stopwords_and_lemmatization(text):
    final_text = []
    text = text.lower()
    text = nltk.word_tokenize(text)

    for word in text:
        if word not in set(stopwords.words('english')):
            lemma = nltk.WordNetLemmatizer()
            word = lemma.lemmatize(word)
            final_text.append(word)
    return " ".join(final_text)

#Total function
def cleaning(text):
    text = remove_html(text)
    text = remove_punctuations(text)
    text = remove_characters(text)
    text = remove_stopwords_and_lemmatization(text)
    return text

#Apply function on text column
data['text']=data['text'].apply(cleaning)

In [22]:
data.head()

                                                text  target
0  politicsnews u budget fight loom republican fl...       1
1  politicsnews u military accept transgender rec...       1
2  politicsnews senior u republican senator let m...       1
3  politicsnews fbi russia probe helped australia...       1
4  politicsnews trump want postal service charge ...       1

In [23]:
X_train, X_test, y_train, y_test = train_test_split(data['text'], data['target'], random_state=0)

In [24]:
max_features = 10000# set()
maxlen = 300# sentence

In [25]:
import tensorflow as tf

#tf.keras.utils.pad_sequences

tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words=max_features)
tokenizer.fit_on_texts(X_train)
tokenized_train = tokenizer.texts_to_sequences(X_train)


X_train = tf.keras.utils.pad_sequences(tokenized_train, maxlen=maxlen)#adding zeros

In [26]:
tokenized_test = tokenizer.texts_to_sequences(X_test)
X_test = tf.keras.utils.pad_sequences(tokenized_test, maxlen=maxlen)

In [27]:
batch_size = 256
epochs = 10
# embed_size = 100

In [28]:
from tensorflow.keras.layers import Dense, Dropout
model = Sequential()
#Non-trainable embeddidng layer
# model.add(Embedding(max_features, output_dim=embed_size, input_length=maxlen, trainable=False))
# #LSTM
# model.add(LSTM(units=128 , return_sequences = True , recurrent_dropout = 0.25 , dropout = 0.25))
# model.add(LSTM(units=64 , recurrent_dropout = 0.1 , dropout = 0.1))
# model.add(Dense(units = 32 , activation = 'relu'))
# model.add(Dense(1, activation='sigmoid'))
# model.compile(optimizer=keras.optimizers.Adam(lr = 0.01), loss='binary_crossentropy', metrics=['accuracy'])
model.add(Dense(units=128, activation='relu', input_dim=maxlen))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model.fit(X_train, y_train, epochs=200, verbose=1)

Epoch 1/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.5426 - loss: 43.1832
Epoch 2/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5486 - loss: 2.3782
Epoch 3/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5521 - loss: 1.3455
Epoch 4/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.5571 - loss: 1.1632
Epoch 5/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5670 - loss: 0.9751
Epoch 6/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5725 - loss: 0.8215
Epoch 7/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5723 - loss: 0.7989
Epoch 8/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5809 - loss: 0.7394
Epoch 9/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.5947 - loss: 0.6905
Epoch 10/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.5944 - loss: 0.6880
Epoch 11/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5928 - loss: 0.6705
Epoch 12/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5863 - loss: 0.6659
Epoch 13/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.5836 - loss: 0.6552
Epoch 14/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.5961 - loss: 0.6486
Epoch 15/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.5955 - loss: 0.6514
Epoch 16/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6018 - loss: 0.6348
Epoch 17/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.5997 - loss: 0.6292
Epoch 18/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6063 - loss: 0.6252
Epoch 19/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.6193 - loss: 0.6270
Epoch 20/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.6293 - loss: 0.6053
Epoch 21/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6383 - loss: 0.6071
Epoch 22/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6388 - loss: 0.5970
Epoch 23/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6457 - loss: 0.5955
Epoch 24/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.6502 - loss: 0.5962
Epoch 25/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.6564 - loss: 0.5947
Epoch 26/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6641 - loss: 0.5777
Epoch 27/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6699 - loss: 0.5718
Epoch 28/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6743 - loss: 0.5676
Epoch 29/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6749 - loss: 0.5696
Epoch 30/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.6807 - loss: 0.5608
Epoch 31/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6819 - loss: 0.5580
Epoch 32/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6827 - loss: 0.5552
Epoch 33/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6870 - loss: 0.5551
Epoch 34/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.6903 - loss: 0.5438
Epoch 35/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6942 - loss: 0.5403
Epoch 36/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6961 - loss: 0.5367
Epoch 37/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7006 - loss: 0.5313
Epoch 38/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6998 - loss: 0.5360
Epoch 39/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.6933 - loss: 0.5366
Epoch 40/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7015 - loss: 0.5281
Epoch 41/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7053 - loss: 0.5189
Epoch 42/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7068 - loss: 0.5184
Epoch 43/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7110 - loss: 0.5124
Epoch 44/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7108 - loss: 0.5113
Epoch 45/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7122 - loss: 0.5147
Epoch 46/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7154 - loss: 0.5125
Epoch 47/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7143 - loss: 0.5137
Epoch 48/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7181 - loss: 0.5018
Epoch 49/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7188 - loss: 0.5011
Epoch 50/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7229 - loss: 0.4937
Epoch 51/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7203 - loss: 0.5019
Epoch 52/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7261 - loss: 0.4943
Epoch 53/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7263 - loss: 0.4914
Epoch 54/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7261 - loss: 0.4888
Epoch 55/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7311 - loss: 0.4834
Epoch 56/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7304 - loss: 0.4810
Epoch 57/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7330 - loss: 0.4834
Epoch 58/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7352 - loss: 0.4790
Epoch 59/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7328 - loss: 0.4822
Epoch 60/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7381 - loss: 0.4749
Epoch 61/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7335 - loss: 0.4900
Epoch 62/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7372 - loss: 0.4768
Epoch 63/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7421 - loss: 0.4684
Epoch 64/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7446 - loss: 0.4679
Epoch 65/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7404 - loss: 0.4708
Epoch 66/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7410 - loss: 0.4602
Epoch 67/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7441 - loss: 0.4573
Epoch 68/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7437 - loss: 0.4571
Epoch 69/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7451 - loss: 0.4592
Epoch 70/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.7469 - loss: 0.4561
Epoch 71/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7499 - loss: 0.4492
Epoch 72/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7498 - loss: 0.4499
Epoch 73/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7480 - loss: 0.4497
Epoch 74/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7512 - loss: 0.4509
Epoch 75/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7534 - loss: 0.4442
Epoch 76/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7558 - loss: 0.4418
Epoch 77/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7535 - loss: 0.4478
Epoch 78/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7542 - loss: 0.4419
Epoch 79/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7577 - loss: 0.4335
Epoch 80/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7588 - loss: 0.4388
Epoch 81/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7586 - loss: 0.4369
Epoch 82/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7577 - loss: 0.4374
Epoch 83/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7617 - loss: 0.4307
Epoch 84/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7633 - loss: 0.4302
Epoch 85/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7634 - loss: 0.4341
Epoch 86/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7602 - loss: 0.4311
Epoch 87/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7649 - loss: 0.4211
Epoch 88/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7642 - loss: 0.4280
Epoch 89/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7649 - loss: 0.4200
Epoch 90/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7681 - loss: 0.4199
Epoch 91/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7665 - loss: 0.4196
Epoch 92/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7681 - loss: 0.4224
Epoch 93/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7652 - loss: 0.4248
Epoch 94/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7664 - loss: 0.4197
Epoch 95/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7700 - loss: 0.4363
Epoch 96/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7708 - loss: 0.4115
Epoch 97/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7653 - loss: 0.4210
Epoch 98/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7705 - loss: 0.4078
Epoch 99/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7717 - loss: 0.4160
Epoch 100/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7715 - loss: 0.4117
Epoch 101/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7742 - loss: 0.4061
Epoch 102/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7747 - loss: 0.4075
Epoch 103/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7750 - loss: 0.4099
Epoch 104/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7750 - loss: 0.4057
Epoch 105/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7751 - loss: 0.4076
Epoch 106/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7759 - loss: 0.4117
Epoch 107/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7800 - loss: 0.3998
Epoch 108/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7782 - loss: 0.4100
Epoch 109/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7798 - loss: 0.3959
Epoch 110/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7827 - loss: 0.3958
Epoch 111/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7799 - loss: 0.4048
Epoch 112/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7816 - loss: 0.3995
Epoch 113/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7828 - loss: 0.3998
Epoch 114/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7815 - loss: 0.3993
Epoch 115/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7812 - loss: 0.4061
Epoch 116/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7847 - loss: 0.3963
Epoch 117/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7870 - loss: 0.3885
Epoch 118/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7850 - loss: 0.3964
Epoch 119/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7841 - loss: 0.3904
Epoch 120/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7893 - loss: 0.3836
Epoch 121/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7894 - loss: 0.3854
Epoch 122/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7857 - loss: 0.3961
Epoch 123/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7874 - loss: 0.3916
Epoch 124/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7870 - loss: 0.3844
Epoch 125/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7870 - loss: 0.3974
Epoch 126/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7904 - loss: 0.3868
Epoch 127/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7914 - loss: 0.3824
Epoch 128/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7878 - loss: 0.3916
Epoch 129/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7894 - loss: 0.3883
Epoch 130/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7921 - loss: 0.3838
Epoch 131/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7927 - loss: 0.3835
Epoch 132/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7907 - loss: 0.3927
Epoch 133/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7943 - loss: 0.3750
Epoch 134/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7951 - loss: 0.3720
Epoch 135/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7945 - loss: 0.3774
Epoch 136/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7920 - loss: 0.3756
Epoch 137/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7966 - loss: 0.3726
Epoch 138/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7948 - loss: 0.3745
Epoch 139/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7931 - loss: 0.3886
Epoch 140/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7938 - loss: 0.3735
Epoch 141/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7976 - loss: 0.3680
Epoch 142/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7975 - loss: 0.3665
Epoch 143/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7951 - loss: 0.3961
Epoch 144/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7953 - loss: 0.3716
Epoch 145/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7978 - loss: 0.3710
Epoch 146/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7989 - loss: 0.3665
Epoch 147/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7993 - loss: 0.3710
Epoch 148/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7975 - loss: 0.3736
Epoch 149/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7995 - loss: 0.3625
Epoch 150/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8020 - loss: 0.3642
Epoch 151/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7998 - loss: 0.3744
Epoch 152/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8027 - loss: 0.3607
Epoch 153/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8022 - loss: 0.3670
Epoch 154/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.7992 - loss: 0.3741
Epoch 155/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8025 - loss: 0.3685
Epoch 156/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8036 - loss: 0.3607
Epoch 157/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8038 - loss: 0.3661
Epoch 158/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.8042 - loss: 0.3597
Epoch 159/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8033 - loss: 0.3637
Epoch 160/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8014 - loss: 0.3684
Epoch 161/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.8066 - loss: 0.3579
Epoch 162/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8051 - loss: 0.3629
Epoch 163/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8032 - loss: 0.3636
Epoch 164/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8074 - loss: 0.3600
Epoch 165/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8080 - loss: 0.3554
Epoch 166/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8082 - loss: 0.3631
Epoch 167/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8086 - loss: 0.3507
Epoch 168/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8084 - loss: 0.3509
Epoch 169/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8108 - loss: 0.3472
Epoch 170/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8101 - loss: 0.3458
Epoch 171/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8101 - loss: 0.3498
Epoch 172/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8104 - loss: 0.3519
Epoch 173/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8085 - loss: 0.3551
Epoch 174/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8112 - loss: 0.3496
Epoch 175/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8124 - loss: 0.3436
Epoch 176/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8132 - loss: 0.3506
Epoch 177/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8118 - loss: 0.3556
Epoch 178/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8135 - loss: 0.3546
Epoch 179/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8148 - loss: 0.3501
Epoch 180/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8148 - loss: 0.3453
Epoch 181/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8153 - loss: 0.3403
Epoch 182/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8173 - loss: 0.3412
Epoch 183/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8068 - loss: 0.3620
Epoch 184/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8105 - loss: 0.3516
Epoch 185/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8162 - loss: 0.3390
Epoch 186/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8181 - loss: 0.3385
Epoch 187/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8164 - loss: 0.3451
Epoch 188/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8167 - loss: 0.3415
Epoch 189/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8090 - loss: 0.3492
Epoch 190/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8188 - loss: 0.3358
Epoch 191/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8159 - loss: 0.3425
Epoch 192/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.8182 - loss: 0.3360
Epoch 193/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8166 - loss: 0.3398
Epoch 194/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8169 - loss: 0.3364
Epoch 195/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8176 - loss: 0.3382
Epoch 196/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8163 - loss: 0.3416
Epoch 197/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8167 - loss: 0.3347
Epoch 198/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8195 - loss: 0.3351
Epoch 199/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8189 - loss: 0.3302
Epoch 200/200
1053/1053 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.8184 - loss: 0.3398

In [29]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │        38,528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 140,549 (549.02 KB)

 Trainable params: 46,849 (183.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 93,700 (366.02 KB)

In [30]:
print("Accuracy of the model on Training Data is - " , model.evaluate(X_train,y_train)[1]*100 , "%")
print("Accuracy of the model on Testing Data is - " , model.evaluate(X_test,y_test)[1]*100 , "%")

1053/1053 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8193 - loss: 0.3318
Accuracy of the model on Training Data is -  81.92617297172546 %
351/351 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6459 - loss: 2.6237
Accuracy of the model on Testing Data is -  64.58797454833984 %

In [31]:
model.save('basic_model.keras')